name: Packer AMI Build
run-name: ${{ github.actor }} is building Packer
on:
  pull_request:
    types:
      - closed
jobs:
  packer-build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # use Java17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: maven
      # use Maven
      - name: Build Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: Move file from target/
        run: mv target/webapp-0.0.1-SNAPSHOT.jar .

      - name: set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      # Build Packer
      - name: build AMI with packer
        run: packer build ami.pkr.hcl

