name: Web Application and Packer Validation
run-name: ${{ github.actor }} is testing Web Application and Packer Validation
on: #when to begin test
  pull_request:
    branches: [ main ]

env:
  ENVIRONMENT: mariadb
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      # use mysql
      - name: Set up MariaDB/MySQL
        uses: getong/mariadb-action@v1.1
        with:
          mariadb version: '10.5.10' # Optional, default value is "latest". The version of the MariaDB
          mysql root password: ${{ secrets.RootPassword }}

      # cache maven
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      # use Java17
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          cache: maven

      # use Maven
      - name: Build Maven
        run: mvn -B package --file pom.xml

      # Set up AWS credentials
      - name: set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init
          target: config.pkr.hcl

      # Validate Packer
      - name: Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami.pkr.hcl